# Generated by Django 2.2.6 on 2021-01-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0002_directorymember_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='branch',
            field=models.CharField(blank=True, choices=[('BADMİNTON', 'BADMİNTON')], max_length=128, null=True, verbose_name='Branş'),
        ),
    ]
